services:

  camera-1:
    build: .
    container_name: keelson-connector-camera
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    command: "--log-level 10 -r rise -e storakrabban -s axis-1 --camera-url rtsp://root:RISE2020@192.168.3.11/axis-media/media.amp?camera=1 --send jpeg"
    
